export interface SimulationScenario {
  id: string; label: string; area: string; specialist: string; alert: string;
  review: string; finding: string; evidence: string; recommendation: string;
  impact: string; verification: string; undo: string;
}
export const SIMULATION_SCENARIOS: SimulationScenario[] = [
  { id: 'ssh', label: 'SSH password guessing', area: 'Identity', specialist: 'Identity investigator', alert: 'Repeated failed SSH logins on training-linux-01 from 198.51.100.241.', review: 'Checking failed logins, source correlation, and successful authentication.', finding: 'Repeated failures against a nonexistent account; no success in the fixture. Compromise is not established.', evidence: 'SIM-EV-SSH-01', recommendation: 'Temporarily block 198.51.100.241', impact: 'Deny this source on training-linux-01 only; other sources remain allowed.', verification: 'Source denied; legitimate SSH connectivity preserved.', undo: 'Remove the operation-owned block rule.' },
  { id: 'ransomware', label: 'Ransomware-like file changes', area: 'Endpoint', specialist: 'Endpoint investigator', alert: 'Rapid file rewrites and ransom-note-like content on training-workstation-02.', review: 'Correlating sample process activity with file changes and backup coverage.', finding: 'One sample process rewrote multiple documents. Encryption and recovery completeness remain unverified.', evidence: 'SIM-EV-FILES-01', recommendation: 'Temporarily isolate training-workstation-02', impact: 'Interrupt workstation network access while preserving the sample management channel. Active user sessions may be disrupted.', verification: 'Lateral connections denied; management channel available. File restoration remains unverified.', undo: 'Remove only the operation-owned isolation policy; do not restore or delete files.' },
  { id: 'remote', label: 'Suspicious remote access', area: 'Network', specialist: 'Network investigator', alert: 'Unexpected remote-access sessions from 198.51.100.242 to training-server-03.', review: 'Comparing sample flows, remote service inventory, and administrative access expectations.', finding: 'Repeated remote-access sessions from a source absent from the fixture allowlist. Intent is unconfirmed.', evidence: 'SIM-EV-FLOW-01', recommendation: 'Temporarily restrict source 198.51.100.242', impact: 'Restrict the sample source on training-server-03 only; legitimate management sources remain permitted.', verification: 'Sample remote-access source denied; management connectivity preserved.', undo: 'Remove only the operation-owned source restriction.' },
  { id: 'admin', label: 'Unexpected admin account change', area: 'Identity', specialist: 'Identity investigator', alert: 'Unapproved administrator group membership for training-user-04.', review: 'Checking the sample account-change audit and approved change records.', finding: 'The fixture shows a new administrator grant without a matching approved change; account takeover is unconfirmed.', evidence: 'SIM-EV-ACCOUNT-01', recommendation: 'Temporarily suspend training-user-04 privileged access', impact: 'Suspend sample privileged access; administrative work by this account is interrupted. Preserve break-glass access.', verification: 'Sample privileged access denied; break-glass account remains available.', undo: 'Restore the previous sample grant only if no intervening account change occurred; otherwise require review.' },
  { id: 'application', label: 'Application exploit probe', area: 'Applications and data', specialist: 'Application / API investigator', alert: 'Suspicious requests against training-api-05 from 198.51.100.243.', review: 'Correlating request patterns, errors, service versions, and host observations.', finding: 'Exploit-like requests are present. No successful code execution is established by the sample logs.', evidence: 'SIM-EV-REQUEST-01', recommendation: 'Temporarily block the probe source at training-api-05', impact: 'Block the sample source at the application edge; preserve normal health checks and other users.', verification: 'Probe source denied; legitimate requests and health checks succeed. Exploit success remains unverified.', undo: 'Remove only the operation-owned application-edge rule.' },
  { id: 'exfiltration', label: 'Unusual outbound data transfer', area: 'Network', specialist: 'Network investigator', alert: 'Unexpected outbound transfer from training-data-06 to 203.0.113.44.', review: 'Comparing sample egress volume, destination history, and authorized transfer records.', finding: 'The sample destination and volume differ from baseline. Content sensitivity and actual data loss are unverified.', evidence: 'SIM-EV-EGRESS-01', recommendation: 'Temporarily restrict egress to 203.0.113.44', impact: 'Restrict this destination from training-data-06; any legitimate transfer to that destination is interrupted.', verification: 'Sample destination unreachable; approved destinations remain reachable. Data loss remains unverified.', undo: 'Remove only the operation-owned destination restriction.' },
];
