"""Closed-Loop Detection Engineering Advisor ("Self-Tuning SOC") for TERMINUS.

Automatically analyzes resolved False Positive incidents and generates tuned
Sigma detection rules and Wazuh XML rule adjustments to eliminate future noise.
"""

from __future__ import annotations

import re
import secrets
from dataclasses import dataclass
from typing import Any


@dataclass
class TuningRecommendation:
    rule_id: str
    name: str
    incident_id: str
    rationale: str
    sigma_yaml: str
    wazuh_xml: str
    suggested_action: str


class DetectionTuningAdvisor:
    """Synthesizes precision detection rules and SIEM exclusion filters."""

    @classmethod
    def generate_tuning_for_incident(
        cls,
        incident: dict[str, Any],
        false_positive_reason: str = "Benign administrative routine activity.",
    ) -> TuningRecommendation:
        rule_id = f"tune-{secrets.token_hex(4)}"
        inc_id = str(incident.get("ticket_id") or incident.get("id") or "unknown")
        orig_rule_id = str(incident.get("rule_id") or "100010")
        desc = str(incident.get("rule_description") or incident.get("summary") or "Security Alert")
        agent_name = str(incident.get("agent_name") or "prod-server")
        raw_log = str(incident.get("full_log") or "")

        # Extract process or user if found
        user_match = re.search(r"user\s+['\"]?([A-Za-z0-9_.-]+)['\"]?", raw_log, re.IGNORECASE)
        user_val = user_match.group(1) if user_match else "svc_backup_admin"

        sigma_content = f"""title: Suppressed: {desc} (Tuned for {agent_name})
id: {rule_id}
status: experimental
description: Auto-tuned detection rule generated by Terminus AI SOC to filter false positives.
references:
    - https://terminus.local/incidents/{inc_id}
author: Terminus Self-Tuning SOC
date: 2026/10/02
logsource:
    category: process_creation
    product: linux
detection:
    selection:
        Image|endswith:
            - '/usr/bin/python3'
            - '/bin/bash'
    filter_benign:
        User: '{user_val}'
        Host: '{agent_name}'
    condition: selection and not filter_benign
falsepositives:
    - Scheduled administrative maintenance tasks
level: medium
"""

        wazuh_content = f"""<!-- Terminus Auto-Tuned Rule: Ref {inc_id} -->
<group name="terminus,custom_tuning,">
  <rule id="19{secrets.token_hex(2)}" level="0">
    <if_sid>{orig_rule_id}</if_sid>
    <hostname>{agent_name}</hostname>
    <match>{user_val}</match>
    <description>Terminus Override: Suppress benign false-positive on {agent_name} for {user_val}</description>
  </rule>
</group>
"""

        return TuningRecommendation(
            rule_id=rule_id,
            name=f"Rule Suppression: {desc[:40]}",
            incident_id=inc_id,
            rationale=f"Incident {inc_id} flagged as False Positive: {false_positive_reason}. Rule excludes user '{user_val}' on host '{agent_name}'.",
            sigma_yaml=sigma_content,
            wazuh_xml=wazuh_content,
            suggested_action="Deploy Wazuh XML to /var/ossec/etc/rules/local_rules.xml and reload manager.",
        )
