"""Interactive setup wizard and database configuration builder for Terminus Engine."""

from __future__ import annotations

from pathlib import Path

from terminus.licensing.service import LicenseService
from terminus.licensing.tiers import TIER_FEATURES, LicenseTier


def main() -> None:
    """Run the interactive Terminus setup wizard."""
    print("=" * 80)
    print(r"""
     _____ _____ ____  __  __ _____ _   _ _   _ ____  
    |_   _| ____|  _ \|  \/  |_   _| \ | | | | / ___| 
      | | |  _| | |_) | |\/| | | | |  \| | | | \___ \ 
      | | | |___|  _ <| |  | | | | | |\  | |_| |___) |
      |_| |_____|_| \_\_|  |_| |_| |_| \_|\___/|____/ 
                                                       
          TERMINUS ENGINE — INTERACTIVE SETUP WIZARD & CONFIG BUILDER
    """)
    print("=" * 80)
    print("\nWelcome to the Terminus Setup Wizard!")
    print("This utility configures your database storage, LLM inference provider, SIEM integrations, and admin environment.\n")

    # 1. Database Configuration
    print("─── STEP 1: Database & Persistence Engine ──────────────────────────")
    print("Select database storage backend:")
    print("  [1] In-Memory (Zero Config / Rapid Development Mode) [Default]")
    print("  [2] SQLite (Single-File Local Database — terminus.db)")
    print("  [3] PostgreSQL (Production Enterprise Multi-Tenant DB)")
    db_choice = input("Enter choice [1-3] (Default: 1): ").strip() or "1"

    db_url = "memory://"
    if db_choice == "2":
        db_file = input("SQLite DB file path [terminus.db]: ").strip() or "terminus.db"
        db_url = f"sqlite:///{db_file}"
        Path(db_file).touch(exist_ok=True)
        print(f"✓ Initialized SQLite database file: {db_file}")
    elif db_choice == "3":
        db_url = input("Enter PostgreSQL Connection URI [postgresql://user:pass@localhost:5432/terminus]: ").strip() or "postgresql://user:pass@localhost:5432/terminus"
        print(f"✓ Configured PostgreSQL database target: {db_url}")
    else:
        print("✓ Selected In-Memory Store for rapid development.")

    print()

    # 2. LLM Provider Configuration
    print("─── STEP 2: AI Investigation LLM Provider ───────────────────────────")
    print("Select AI reasoning engine:")
    print("  [1] Scripted LLM (Offline / Mock Engine for instant testing) [Default]")
    print("  [2] Ollama / vLLM Local Server (http://localhost:11434/v1)")
    print("  [3] OpenAI / Groq API (Cloud API)")
    llm_choice = input("Enter choice [1-3] (Default: 1): ").strip() or "1"

    llm_base_url = "http://localhost:11434/v1"
    llm_api_key = ""
    llm_model = "llama3"

    if llm_choice == "2":
        llm_base_url = input("Ollama/vLLM Base URL [http://localhost:11434/v1]: ").strip() or "http://localhost:11434/v1"
        llm_model = input("Model name [llama3]: ").strip() or "llama3"
    elif llm_choice == "3":
        llm_base_url = input("Cloud API Base URL [https://api.openai.com/v1]: ").strip() or "https://api.openai.com/v1"
        llm_api_key = input("API Key: ").strip()
        llm_model = input("Model name [gpt-4o]: ").strip() or "gpt-4o"
    else:
        print("✓ Selected Scripted Mock LLM engine.")

    print()

    # 3. Wazuh Webhook & Server Port
    print("─── STEP 3: Network & Ingestion Webhook Settings ───────────────────")
    server_port = input("Terminus API Server Port [8000]: ").strip() or "8000"
    wazuh_url = input("Wazuh Manager Webhook URL [http://localhost:8000/wazuh]: ").strip() or "http://localhost:8000/wazuh"
    print(f"✓ Configured server port {server_port} and Wazuh webhook endpoint: {wazuh_url}")

    print()

    # 4. Initial Organization & License
    print("─── STEP 4: Commercial Licensing & Initial Tenant Org ─────────────")
    org_name = input("Initial Organization Name [Acme Security Operations]: ").strip() or "Acme Security Operations"
    admin_email = input("Admin User Email [admin@acme-soc.com]: ").strip() or "admin@acme-soc.com"

    print("\nGenerating cryptographic developer license token...")
    lic_service = LicenseService(secret="terminus-dev-secret-key-32-bytes!!")
    lic_token = lic_service.generate(
        org_id="org-00000001",
        tier=LicenseTier.ENTERPRISE,
        features=TIER_FEATURES[LicenseTier.ENTERPRISE],
        seats=100,
    )
    print("✓ License Tier: ENTERPRISE (100 seats)")
    print(f"✓ License Token: {lic_token[:30]}...")

    print()

    # 5. Save .env Configuration
    print("─── STEP 5: Saving Environment Configuration (.env) ─────────────────")
    env_content = f"""# Terminus Platform Configuration File — Auto-generated by setup.py
DATABASE_URL={db_url}
SERVER_PORT={server_port}
LLM_BASE_URL={llm_base_url}
LLM_API_KEY={llm_api_key}
LLM_MODEL={llm_model}
WAZUH_URL={wazuh_url}
INITIAL_ORG_NAME={org_name}
INITIAL_ADMIN_EMAIL={admin_email}
TERMINUS_LICENSE_TOKEN={lic_token}
"""
    env_path = Path(".env")
    env_path.write_text(env_content, encoding="utf-8")
    print("✓ Successfully created/updated .env file!")

    print("\n" + "=" * 80)
    print("🎉 SETUP COMPLETE!")
    print("=" * 80)
    print("\nYou can now launch the Terminus Engine with:")
    print("  uv run terminus-serve")
    print("\nAccess the Analyst Command Center at:")
    print("  http://localhost:8000/dashboard\n")


if __name__ == "__main__":
    main()
